#  En la carpeta dockercomposeconfig: docker compose up -d
version: '3.8'
services: 
  webapi:
    build:
      context: ./backendBaseDatos-.NET/backendBaseDatos/
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    container_name: "MySQLBasedeDatos"
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: proyecto
      MYSQL_DATABASE: proyectobbdd
    volumes:
      - ./backendBaseDatos-.NET/backendBaseDatos/backBBDDCompose/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - webapi
    build: 
      context: ./frontendangular/


networks:
  mynetwork:
    driver: bridge